#!/usr/bin/env bash
# Configure a ufw firewall to block all incoming traffic
#+ except for TCP ports 22, 443 and 80
sudo apt -y update
sudo apt -y install ufw
sudo ufw enable
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw reload
